export const usersMock = [
  {
    id: 333,
    name: "Alice",
    photo: "https://unsplash.com/photos/Wzj7rBxxMaw",
    country: "USA",
    city: "New York",
    hobbies: ["Reading", "Photography", "Cooking"],
  },
  {
    id: 334,
    name: "Bob",
    photo: "https://unsplash.com/photos/_59aYi9cPUE",
    country: "USA",
    city: "Los Angeles",
    hobbies: ["Surfing", "Music", "Hiking"],
  },
  {
    id: 335,
    name: "Charlie",
    photo: "https://unsplash.com/photos/rigCO5cf22I",
    country: "Canada",
    city: "Toronto",
    hobbies: ["Gaming", "Traveling", "Cycling"],
  },
  {
    id: 336,
    name: "Diana",
    photo: "https://unsplash.com/photos/pIkKUquEEzU",
    country: "Canada",
    city: "Vancouver",
    hobbies: ["Swimming", "Painting", "Yoga"],
  },
  {
    id: 337,
    name: "Eve",
    photo: "https://unsplash.com/photos/qOtd2OW9XV4",
    country: "USA",
    city: "Miami",
    hobbies: ["Dancing", "Gardening", "Writing"],
  },
  {
    id: 338,
    name: "Frank",
    photo: "https://unsplash.com/photos/DEgSQHj42AY",
    country: "Canada",
    city: "Montreal",
    hobbies: ["Fishing", "Skiing", "Cooking"],
  },
  {
    id: 339,
    name: "Grace",
    photo: "https://unsplash.com/photos/kVnTR27tIgw",
    country: "USA",
    city: "Seattle",
    hobbies: ["Photography", "Running", "Crafting"],
  },
  {
    id: 340,
    name: "Hank",
    photo: "https://unsplash.com/photos/Y06imaOLycY",
    country: "Canada",
    city: "Calgary",
    hobbies: ["Hiking", "Camping", "Birdwatching"],
  },
  {
    id: 341,
    name: "Ivy",
    photo: "https://unsplash.com/photos/7_TTPznVIQI",
    country: "USA",
    city: "Chicago",
    hobbies: ["Painting", "Traveling", "Knitting"],
  },
  {
    id: 342,
    name: "Jack",
    photo: "https://unsplash.com/photos/QMRN_GX7p4I",
    country: "Canada",
    city: "Ottawa",
    hobbies: ["Chess", "Cooking", "Writing"],
  },
];
